### ISSUE TITLE
N for exclusion

### ISSUE THREAD

**Issue by mcfrank** [manybabies/mb1-analysis-public#2]
do we include labs with "more than 10 data points" (text) or with >= 10 (code)?

right now we have a conflict, not specified in https://github.com/langcog/mb1-analysis/issues/138 - I think this is me being sloppy with my > vs. >=...

thanks @angelinetsui

thoughts @christinabergmann @melsod @mekline ?

**Comment by mcfrank** [comment]
note that a change to the code here puts madlabucsd out of the dataset. I vote for noting the deviation from prereg and keeping them in.

**Comment by melsod** [comment]
I agree - honestly in colloquial speech "more than ten" is really ambiguous between the two, and I imagine whoever wrote the original text actually meant "ten or more".

**Comment by christinabergmann** [comment]
I also read this as "10 or more" and I did check this chunk in the code for compliance with my reading of the exclusion criteria.

**Comment by christinabergmann** [comment]
P.S. Later on in the preprint it says "An additional XYZ labs registered to participate but failed to collect data from at least 10 included infants, and so their data were not included. Information about all included labs is given in Table 1."

**Comment by mcfrank** [comment]
Noted in the deviations section.
