### ISSUE TITLE
Contrast coding not explicitly given

### ISSUE THREAD

**Issue by palday** [manybabies/mb1-analysis-public#4]
I could not find anywhere in the R code nor accompanying text a specification of the contrast coding. For most factorial designs in psycholinguistics, effect/sum/deviation coding would be more appropriate than the default treatment coding. But in either case, you need to specify in the manuscript the contrast coding because the coefficients are not interpretable without it. Also, you should explicitly convert categorical variables to `factor`s and not just leave them as `character`s because this can have weird knock-on effects elsewhere.

The default `contr.sum` in R has a opaque naming scheme, but the `car` package has an alternative with a more meaningful naming scheme, `contr.Sum`.

Here's a brief example from my own tinkering:

```R
library(car)
# the sort-decreasing step makes contr.Sum/contr.sum more consistent with other 
# contrasts in R and contrasts in Julia
contrasts(d_lmer$trial_type) <- contr.Sum(sort(levels(d_lmer$trial_type),decreasing = TRUE))
contrasts(d_lmer$nae) <- contr.Sum(sort(levels(d_lmer$nae),decreasing = TRUE))
contrasts(d_lmer$method) <- contr.Sum(sort(levels(d_lmer$method),decreasing = TRUE))
```

**Comment by mcfrank** [comment]
Hi Philip,

Thanks very much for your comments. I agree completely about adding
explicit coding information to the ms, and we will do that.

On your other two points:
1. I honestly have never understood why people prefer to move away from
dummy coding most of the time. Maybe I'm a dummy. Seriously, I find the
additive interpretation of coefficients from dummy coding much more
straightforward. Can you point me towards some arguments, or a
recommendation why a particular alternate coding scheme could be useful
here?
2. Why convert strings to factors? stringsasfactors=TRUE
<https://simplystatistics.org/2015/07/24/stringsasfactors-an-unauthorized-biography/>
is a big discussion point. My impression of the tidyverse workflow is to
avoid casting strings to factors whenever possible.

Mike

**Comment by palday** [comment]
1. It matters for the interpretation of interactions, see e.g. [Dale Barr's comments](http://talklab.psy.gla.ac.uk/tvw/catpred/) or my (admittedly tedious) [worked example for a linguistic manipulation](https://www.phillipalday.com/stats/coding.html).

2. When combining and manipulating the data as tables, strings are fine and possibly preferred. But when treating them as variables in a model, then factors are definitely preferred (at least for regression models), because that's the representation the model will actually need. And you can't set contrasts on characters, only on factors. (Although you can somewhat get around that with `options(contrasts=...)` or using the `contrasts=` argument in modelling functions that support that. Treating known categorical variables as factors also has certain debugging advantages for variables whose string representation may be mistakenly purely numeric (e.g. participant ID can be numeric). Sure, you can force these things to be strings instead, but that's not actually representing the structure of your data (a finite set of labels rather than a selection of potentially infinite strings).

**Comment by mcfrank** [comment]
OK, thanks for this - right now we are using dummy coding and I think we'll stick with that, but I have processed your example and noted this for future work!
