### ISSUE TITLE
Preprocessing Issues

### ISSUE THREAD

**Issue by palday** [manybabies/mb1-analysis-public#5]
We've found a small pre-processing issues:
- [x] `subid` isn't unique across labs, so currently the model treats them as partially crossed instead of fully nested. If subjects didn't move between labs, then this is easy to fix: `d_lmer$subid <- interaction(d_lmer$subid, d_lmer$lab)`
- [x] Some of the CSVs encode `NA` as `N/A`. This can be fixed by changing your `read_csv()` calls to `read_csv(...,na=c("","NA","N/A"))`.
- [x] There are a number of parsing errors when reading `02_validated_output.csv`.
- [x] At some point in the manuscript, the number of labs following exclusion is dropped from 69 to 67. But there are still 69 labs in the dataset going into the model (based on running all the code up to the fitting of `mod_lmer`). This isn't  to do with missing levels of a factor either: `length(unique(d_lmer$lab))` still yields 69.  Perhaps this emerges from the parsing errors and things not dropping/merging/etc. like this should. 
- [x] Non monolingual babies are in the monolingual data set.

To the extent that we've been able to work around these, none of these seem to have a real impact on the results, but the nested vs. partially crossed issue for `subid` can have a big impact on compute time.

**Comment by dmbates** [comment]
Perhaps it will help to have a list of the subid values that are repeated in different labs

`"1", "10", "11", "1101", "1104", "1106", "1110", "1111", "1115", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21", "22", "23", "24", "25", "26", "27", "28", "3", "30", "31", "32", "33", "34", "37", "38", "39", "4", "41", "42", "4204", "45", "46", "5", "56", "6", "64", "7", "71", "75", "76", "8", "80", "9", "mb001", "mb002", "mb003", "mb004", "mb005", "mb006", "mb007", "mb008", "mb009", "mb01", "mb010", "mb011", "mb012", "mb013", "mb014", "mb015", "mb016", "mb017", "mb018", "mb019", "mb01b", "mb02", "mb020", "mb021", "mb022", "mb023", "mb024", "mb025", "mb026", "mb027", "mb028", "mb029", "mb03", "mb030", "mb031", "mb032", "mb033", "mb034", "mb035", "mb036", "mb037", "mb038", "mb039", "mb04", "mb040", "mb041", "mb042", "mb043", "mb044", "mb045", "mb046", "mb047", "mb048", "mb05", "mb06", "mb065", "mb066", "mb069", "mb07", "mb070", "mb071", "mb072", "mb073", "mb074", "mb075", "mb076", "mb08", "mb09", "mb0903", "mb1", "mb10", "mb1002", "mb102", "mb103", "mb104", "mb105", "mb107", "mb108", "mb11", "mb1103", "mb12", "mb1201", "mb1202", "mb1203", "mb1204", "mb1205", "mb1206", "mb1207", "mb1208", "mb13", "mb14", "mb15", "mb16", "mb17", "mb18", "mb19", "mb2", "mb20", "mb21", "mb22", "mb23", "mb24", "mb25", "mb26", "mb27", "mb28", "mb29", "mb3", "mb30", "mb31", "mb32", "mb33", "mb34", "mb35", "mb36", "mb37", "mb38", "mb39", "mb4", "mb40", "mb41", "mb42", "mb43", "mb45", "mb46", "mb48", "mb49", "mb5", "mb50", "mb6", "mb7", "mb8", "mb9", "p01", "p02", "s01", "s02", "s03", "s04", "s05", "s06", "s07", "s08", "s09", "s10", "s11", "s12", "s13", "s14", "s15", "s16", "s17", "s18", "s19", "s20", "s21", "s22", "s23", "s25", "s26", "s27", "s28", "s29", "s30", "s31", "s32", "s33", "s34"`

For some reason "mb10" is the most popular subject label, used in 13 labs
`"babylabbrookes"     
 "babylabkonstanz"    
 "baldwinlabuoregon"  
 "cdcceu"             
 "childlabmanchester" 
 "escompicbsleipzig"  
 "kokuhamburg"        
 "lcduleeds"          
 "madlabucsd"         
 "minddevlabbicocca"  
 "musdevutm"          
 "pocdnorthwestern"   
 "weescienceedinburgh"`

`

**Comment by dmbates** [comment]
I think I saw in the manuscript that each lab used only one method but there are five labs that use multiple methods

> 
│ 1   │ babylabpotsdam          │ hpp          │
│ 2   │ babylabpotsdam          │ singlescreen │
│ 3   │ infantcogubc            │ singlescreen │
│ 4   │ infantcogubc            │ eyetracking  │
│ 5   │ lancaster               │ singlescreen │
│ 6   │ lancaster               │ eyetracking  │
│ 7   │ ldlottawa               │ singlescreen │
│ 8   │ ldlottawa               │ eyetracking  │
│ 9   │ nusinfantlanguagecentre │ eyetracking  │
│ 10  │ nusinfantlanguagecentre │ singlescreen │

**Comment by mcfrank** [comment]
Thanks for these extremely helpful comments! I do think the ms acknowledges
the multi-method labs (e.g., in the table of participating labs) but I will
check if there is a presupposition of choice.

@philip great catches, I will work on these when we next take up the
revisions!

**Comment by christinabergmann** [comment]
Re: monolingual some more info (after having to remember myself)
Labs might differ in their definition, so we re-calculated monolingual status and added the column `monolingual` (so there might still be participants where it says bilingual in `lang_group`).

**Comment by mcfrank** [comment]
thanks, have addressed these.

- subid_unique used for lmers
- read csv issue fixed, thanks
- parsing errors are dealt with once validation happens
- I believe this mismatch was due to the `child="exclusions.Rmd"` issue in #8 
- as @christinabergmann says, this is a categorization issue dealt with in variable validation
