### ISSUE TITLE
Non-error trials with zero looking time

### ISSUE THREAD

**Issue by palday** [manybabies/mb1-analysis-public#7]
There are trials where `trial_error == FALSE` but `looking_time == 0`. It's not clear whether this reflects a preprocessing error or just a 'correct' trial (no equipment issue, no interference from parents, etc.) where the baby never looked/fixated at the target. Beyond the inferential issues, there's also the problem that `log 0` isn't a real number.

Depending on the cause of this constellation and your inferential question, there are a few possibilities:

- Replace the 0's with `NA`.
- Replace the 0 with some small epsilon (e.g. 1ms).
- Add some small epsilon to all looking times.
- Model the "look vs. no look" as a separate part of the data generation process, e.g. as a separate binomial model or in a hybrid hurdle model.

I'm raising this as a separate issue to the list in #5 because I think it might warrant some discussion before implementing a solution.

**Comment by christinabergmann** [comment]
There should be a column called short_lt which is set to FALSE when looking times are above 2s, i.e. only those should be included. 
Cf. https://github.com/manybabies/mb1-analysis-public/blob/master/paper/exclusions.Rmd l 119-128

**Comment by mcfrank** [comment]
I can't reproduce this error in my own version of the pipeline - perhaps again due to the exclusions issue covered in #8?
