### ISSUE TITLE
Processed data files

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1-analysis-public#9]
Files in processed data folder 01_ 02_ and _03 do not seem match files generated when 01_, 02_, 03_ scripts re-run from scratch. Do the updated processed data files just need to be pushed, or is this symptom of something else?

I noticed this working on MB1B - there seem to be duplicate trial pairs in processed_data/03_data_trial_main.csv pulled from repo, but not when same file is generated from the script.

**Comment by mcfrank** [comment]
Not sure where this crept in, but all files are regenerated in the current build
